export const GAME_BALANCE = {
  BASE_AP: 6,
  NURSE_PERK_AP_BONUS: 2,
  MAX_AP_DEFAULT: 6,
  MAX_AP_WITH_PERK: 8,
  ATTENDING_RATING: {
    CORRECT_BOOST: 2,
    PENALTY_FOG_TRAP: 6,
    PENALTY_TRIAGE_TRAP: 4,
    CORRECT_TRIAGE_BOOST: 1,
    DEFAULT_START: 96,
  },
  XP_REWARDS: {
    FOG_CORRECT: 50,
    FOG_CORRECT_PHARMACIST: 65,
    FOG_INCORRECT: 10,
    TRIAGE_CORRECT: 25,
    TRIAGE_INCORRECT: 5,
    SHIFT_COMPLETION: 100,
    ANKI_CARD_REVIEW: 15,
  },
} as const;
